env:
  es2021: true
extends:
  - airbnb-base
  - airbnb-base/legacy
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: 0,
  import/extensions: 0,
  import/prefer-default-export: 0,
  comma-dangle: 0
}
